### ISSUE TITLE
The project needs an update

### ISSUE THREAD

**Issue by midou221** [materight/streamcorn#1]
All websites in the app have stopped working
Also, openload, SWZZ, rapidcrypt and many servers has have been suspended
I think the project needs updating

Please continue to develop it And add an English watch source

**Comment by materight** [comment]
Unfortunately I'm currently working on different projects and I don't have much time left to work on this app. However, I gladly accept pull requests if you want to contribute!

**Comment by midou221** [comment]
thank u very much
i'll try to contribute, but don't expect too much from me
